!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.8	//
CMD_DEL	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_DEL = 13,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_EXPIRE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_EXPIRE = 14,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_GET	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_GET = 1,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_HGETALL	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_HGETALL = 19,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_HINCRBY	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_HINCRBY = 18,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_HMGET	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_HMGET = 20,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_HMSET	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_HMSET = 22,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_INCR	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_INCR = 11,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_INCRBY	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        CMD_INCRBY = 29,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_NULL	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_NULL = 0,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_SADD	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SADD = 3,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_SCARD	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SCARD = 5,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_SET	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SET = 2,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_SETEX	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        CMD_SETEX = 30,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_SETNX	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SETNX = 12,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_SISMEMBER	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SISMEMBER = 7,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_SMEMBERS	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SMEMBERS = 4,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_SREM	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SREM = 6,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_TYPE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	enum CMD_TYPE$/;"	g	namespace:CRedisPro
CMD_ZADD	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZADD = 8,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_ZCARD	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZCARD = 9,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_ZCOUNT	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZCOUNT = 27,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_ZINCRBY	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZINCRBY = 23,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_ZRANGE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZRANGE = 10,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_ZRANGEBYSCORE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZRANGEBYSCORE = 16,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_ZRANK	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZRANK = 25,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_ZREM	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZREM = 15,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_ZREMRANGEBYRANK	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZREMRANGEBYRANK = 26,     $/;"	e	enum:CRedisPro::CMD_TYPE
CMD_ZREVRANGE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZREVRANGE = 28,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_ZREVRANGEBYSCORE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZREVRANGEBYSCORE = 17,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_ZREVRANK	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZREVRANK = 24,$/;"	e	enum:CRedisPro::CMD_TYPE
CMD_ZSCORE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZSCORE = 21,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^namespace CRedisPro $/;"	n
CRedisPro::CMD_DEL	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_DEL = 13,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_EXPIRE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_EXPIRE = 14,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_GET	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_GET = 1,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_HGETALL	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_HGETALL = 19,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_HINCRBY	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_HINCRBY = 18,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_HMGET	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_HMGET = 20,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_HMSET	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_HMSET = 22,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_INCR	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_INCR = 11,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_INCRBY	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        CMD_INCRBY = 29,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_NULL	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_NULL = 0,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_SADD	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SADD = 3,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_SCARD	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SCARD = 5,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_SET	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SET = 2,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_SETEX	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        CMD_SETEX = 30,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_SETNX	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SETNX = 12,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_SISMEMBER	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SISMEMBER = 7,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_SMEMBERS	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SMEMBERS = 4,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_SREM	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_SREM = 6,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_TYPE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	enum CMD_TYPE$/;"	g	namespace:CRedisPro
CRedisPro::CMD_ZADD	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZADD = 8,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_ZCARD	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZCARD = 9,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_ZCOUNT	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZCOUNT = 27,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_ZINCRBY	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZINCRBY = 23,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_ZRANGE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZRANGE = 10,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_ZRANGEBYSCORE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZRANGEBYSCORE = 16,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_ZRANK	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZRANK = 25,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_ZREM	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZREM = 15,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_ZREMRANGEBYRANK	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZREMRANGEBYRANK = 26,     $/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_ZREVRANGE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZREVRANGE = 28,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_ZREVRANGEBYSCORE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZREVRANGEBYSCORE = 17,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_ZREVRANK	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZREVRANK = 24,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::CMD_ZSCORE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_ZSCORE = 21,$/;"	e	enum:CRedisPro::CMD_TYPE
CRedisPro::ERROR_TYPE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    enum ERROR_TYPE$/;"	g	namespace:CRedisPro
CRedisPro::ERR_PACKAGE_INCOMPLETE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        ERR_PACKAGE_INCOMPLETE  = -1003, $/;"	e	enum:CRedisPro::ERROR_TYPE
CRedisPro::OPTION	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    enum OPTION$/;"	g	namespace:CRedisPro
CRedisPro::PACKAGE_COMPLETE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        PACKAGE_COMPLETE = -1001, $/;"	e	enum:CRedisPro::ERROR_TYPE
CRedisPro::TOK_IGNORE_EMPTY	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        TOK_IGNORE_EMPTY = 2,$/;"	e	enum:CRedisPro::OPTION
CRedisPro::TOK_TRIM	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        TOK_TRIM = 1,$/;"	e	enum:CRedisPro::OPTION
CRedisPro::check_packet	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int check_packet(const char *buf, int len); $/;"	p	namespace:CRedisPro	signature:(const char *buf, int len)
CRedisPro::pack	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack(const redisRequest &stReq, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const redisRequest &stReq, char *pszBuf, int &iLen)
CRedisPro::pack	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack(const string &key, const string &binary, char *buffer, int &len);$/;"	p	namespace:CRedisPro	signature:(const string &key, const string &binary, char *buffer, int &len)
CRedisPro::pack	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack(const string &key, const string &binary, const string &time, char *buffer, int &len);$/;"	p	namespace:CRedisPro	signature:(const string &key, const string &binary, const string &time, char *buffer, int &len)
CRedisPro::pack	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack(vector<string> &vecQuery, char *buffer, int &len);$/;"	p	namespace:CRedisPro	signature:(vector<string> &vecQuery, char *buffer, int &len)
CRedisPro::pack_del	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_del(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
CRedisPro::pack_expire	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_expire(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
CRedisPro::pack_get	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_get(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
CRedisPro::pack_hclear	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_hclear(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
CRedisPro::pack_hgetall	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_hgetall(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
CRedisPro::pack_hincrby	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_hincrby(const string &strKey, const string &strField, const string &strCount, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strField, const string &strCount, char *pszBuf, int &iLen)
CRedisPro::pack_hmget	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_hmget(const string &strKey, const vector<string> &vecFields, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const vector<string> &vecFields, char *pszBuf, int &iLen)
CRedisPro::pack_hmset	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_hmset(const string &strKey, const map<string, string> &mapField2Value, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const map<string, string> &mapField2Value, char *pszBuf, int &iLen)
CRedisPro::pack_incr	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_incr(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
CRedisPro::pack_incrby	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_incrby(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
CRedisPro::pack_sadd	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_sadd(const string &strKey, const vector<string> &vecElems, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const vector<string> &vecElems, char *pszBuf, int &iLen)
CRedisPro::pack_scard	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_scard(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
CRedisPro::pack_set	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_set(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
CRedisPro::pack_setex	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_setex(const string &strKey, const string &strValue, const string &strTime, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, const string &strTime, char *pszBuf, int &iLen)
CRedisPro::pack_setnx	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_setnx(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
CRedisPro::pack_sismember	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_sismember(const string &strKey, const string &strElem, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strElem, char *pszBuf, int &iLen)
CRedisPro::pack_smembers	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_smembers(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
CRedisPro::pack_srem	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_srem(const string &strKey, const vector<string> &vecElems, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const vector<string> &vecElems, char *pszBuf, int &iLen)
CRedisPro::pack_zadd	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_zadd(const string &strKey, const string &strScore, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strScore, const string &strValue, char *pszBuf, int &iLen)
CRedisPro::pack_zcard	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_zcard(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
CRedisPro::pack_zcount	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zcount(const string &strKey, const string &strStart, const string &strEnd, bool bLessFlag, bool bGreateFlag, bool bIsSsdbFlag, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strStart, const string &strEnd, bool bLessFlag, bool bGreateFlag, bool bIsSsdbFlag, char *pszBuf, int &iLen)
CRedisPro::pack_zincrby	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zincrby(const string &strKey, const string &strField, const string &strCount, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strField, const string &strCount, char *pszBuf, int &iLen)
CRedisPro::pack_zrange	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrange(const string &strKey, const string &strStart, const string &strEnd, char *pszBuf, int &iLen, bool bWithScores=false);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strStart, const string &strEnd, char *pszBuf, int &iLen, bool bWithScores=false)
CRedisPro::pack_zrangebyscore	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrangebyscore(const string &strKey, const string &strStart, const string &strEnd, const string &strLimit, bool bWithScores, bool bLessFlag, bool bGreateFlag, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strStart, const string &strEnd, const string &strLimit, bool bWithScores, bool bLessFlag, bool bGreateFlag, char *pszBuf, int &iLen)
CRedisPro::pack_zrank	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrank(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
CRedisPro::pack_zrem	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrem(const string &strKey, const vector<string> &vecValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const vector<string> &vecValue, char *pszBuf, int &iLen)
CRedisPro::pack_zremrangebyrank	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zremrangebyrank(const string &strKey, const string &strStart, const string &strEnd, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strStart, const string &strEnd, char *pszBuf, int &iLen)
CRedisPro::pack_zrevrange	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrevrange(const string &strKey, const string &strStart, const string &strEnd, char *pszBuf, int &iLen, bool bWithScores=false);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strStart, const string &strEnd, char *pszBuf, int &iLen, bool bWithScores=false)
CRedisPro::pack_zrevrangebyscore	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrevrangebyscore(const string &strKey, const string &strStart, const string &strEnd, const string &strLimit, bool bWithScores, bool bLessFlag, bool bGreateFlag, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strStart, const string &strEnd, const string &strLimit, bool bWithScores, bool bLessFlag, bool bGreateFlag, char *pszBuf, int &iLen)
CRedisPro::pack_zrevrank	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrevrank(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
CRedisPro::pack_zscore	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zscore(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
CRedisPro::printRedisReply	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    string printRedisReply(const redisReply &reply);$/;"	p	namespace:CRedisPro	signature:(const redisReply &reply)
CRedisPro::process_bulk_item	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int process_bulk_item(string::const_iterator &pos, string::const_iterator end, redisReply &reply);$/;"	p	namespace:CRedisPro	signature:(string::const_iterator &pos, string::const_iterator end, redisReply &reply)
CRedisPro::process_item	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int process_item(string::const_iterator &pos, string::const_iterator end, redisReply &reply);$/;"	p	namespace:CRedisPro	signature:(string::const_iterator &pos, string::const_iterator end, redisReply &reply)
CRedisPro::process_line_item	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int process_line_item(string::const_iterator &pos, string::const_iterator end, redisReply &reply);$/;"	p	namespace:CRedisPro	signature:(string::const_iterator &pos, string::const_iterator end, redisReply &reply)
CRedisPro::process_multi_bulk_item	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int process_multi_bulk_item(string::const_iterator &pos, string::const_iterator end, redisReply &reply);$/;"	p	namespace:CRedisPro	signature:(string::const_iterator &pos, string::const_iterator end, redisReply &reply)
CRedisPro::redisReply	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    struct redisReply$/;"	s	namespace:CRedisPro
CRedisPro::redisReply::element	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        vector<redisReply> element; $/;"	m	struct:CRedisPro::redisReply	access:public
CRedisPro::redisReply::elements	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        int elements;$/;"	m	struct:CRedisPro::redisReply	access:public
CRedisPro::redisReply::integer	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        long long integer;$/;"	m	struct:CRedisPro::redisReply	access:public
CRedisPro::redisReply::len	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        int len;$/;"	m	struct:CRedisPro::redisReply	access:public
CRedisPro::redisReply::redisReply	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        redisReply()$/;"	f	struct:CRedisPro::redisReply	access:public	signature:()
CRedisPro::redisReply::str	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        string str;$/;"	m	struct:CRedisPro::redisReply	access:public
CRedisPro::redisReply::type	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        int type;$/;"	m	struct:CRedisPro::redisReply	access:public
CRedisPro::redisRequest	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	struct redisRequest$/;"	s	namespace:CRedisPro
CRedisPro::redisRequest::bGreateFlag	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		bool bGreateFlag;						\/\/sorted set数据类型里zrangebyscore等命令的参数，是否需要取右边的开区间标志位$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::bIsSsdbFlag	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		bool bIsSsdbFlag;						\/\/是否为ssdb协议，因为ssdb与redis存在细微的差别。			$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::bLessFlag	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		bool bLessFlag;							\/\/sorted set数据类型里zrangebyscore等命令的参数，是否需要取左边的开区间标志位$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::bWithScores	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		bool bWithScores;						\/\/sorted set数据类型里zrangebyscore等命令的参数，是否需要携带score标志位$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::eCmdType	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_TYPE eCmdType;						\/\/redis操作命令类型$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::mapField2Value	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		map<string, string> mapField2Value;		\/\/hash数据类型的key->value列表$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::redisRequest	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		redisRequest()$/;"	f	struct:CRedisPro::redisRequest	access:public	signature:()
CRedisPro::redisRequest::strEnd	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strEnd;							\/\/sorted set数据类型里zrangebyscore等命令的参数，结束权重$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::strField	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strField;						\/\/hash数据类型的域字段值。$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::strKey	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strKey;							\/\/数据的key$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::strLimit	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strLimit;						\/\/sorted set数据类型里zrangebyscore等命令的参数，限制字段$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::strScore	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strScore;						\/\/sorted set数据类型的权重值$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::strStart	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strStart;						\/\/sorted set数据类型里zrangebyscore等命令的参数，起始权重$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::strTime	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strTime;							\/\/过期时间$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::strValue	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strValue;						\/\/value字段$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::vecField	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		vector<string> vecField;				\/\/hash数据类型的域字段列表。$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::vecKey	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		vector<string> vecKey;					\/\/string时批量处理的key$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::redisRequest::vecValue	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		vector<string> vecValue;				\/\/hash或者sorted set数据类型的值字段列表。$/;"	m	struct:CRedisPro::redisRequest	access:public
CRedisPro::seek_new_line	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int seek_new_line(string::const_iterator pos, string::const_iterator end, string::const_iterator &res);$/;"	p	namespace:CRedisPro	signature:(string::const_iterator pos, string::const_iterator end, string::const_iterator &res)
CRedisPro::unpack	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int unpack(const string &buffer, int len, redisReply &reply);$/;"	p	namespace:CRedisPro	signature:(const string &buffer, int len, redisReply &reply)
CRedisPro::unpack	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int unpack(const string &rspbuffer, vector<redisReply> &vecReply, string &restbuffer);$/;"	p	namespace:CRedisPro	signature:(const string &rspbuffer, vector<redisReply> &vecReply, string &restbuffer)
ERROR_TYPE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    enum ERROR_TYPE$/;"	g	namespace:CRedisPro
ERR_PACKAGE_INCOMPLETE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        ERR_PACKAGE_INCOMPLETE  = -1003, $/;"	e	enum:CRedisPro::ERROR_TYPE
OPTION	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    enum OPTION$/;"	g	namespace:CRedisPro
PACKAGE_COMPLETE	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        PACKAGE_COMPLETE = -1001, $/;"	e	enum:CRedisPro::ERROR_TYPE
REDIS_PROTOCOL_H	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	2;"	d
REDIS_REPLY_ARRAY	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	12;"	d
REDIS_REPLY_ERROR	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	16;"	d
REDIS_REPLY_INTEGER	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	13;"	d
REDIS_REPLY_NIL	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	14;"	d
REDIS_REPLY_STATUS	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	15;"	d
REDIS_REPLY_STRING	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	11;"	d
TOK_IGNORE_EMPTY	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        TOK_IGNORE_EMPTY = 2,$/;"	e	enum:CRedisPro::OPTION
TOK_TRIM	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        TOK_TRIM = 1,$/;"	e	enum:CRedisPro::OPTION
bGreateFlag	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		bool bGreateFlag;						\/\/sorted set数据类型里zrangebyscore等命令的参数，是否需要取右边的开区间标志位$/;"	m	struct:CRedisPro::redisRequest	access:public
bIsSsdbFlag	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		bool bIsSsdbFlag;						\/\/是否为ssdb协议，因为ssdb与redis存在细微的差别。			$/;"	m	struct:CRedisPro::redisRequest	access:public
bLessFlag	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		bool bLessFlag;							\/\/sorted set数据类型里zrangebyscore等命令的参数，是否需要取左边的开区间标志位$/;"	m	struct:CRedisPro::redisRequest	access:public
bWithScores	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		bool bWithScores;						\/\/sorted set数据类型里zrangebyscore等命令的参数，是否需要携带score标志位$/;"	m	struct:CRedisPro::redisRequest	access:public
check_packet	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int check_packet(const char *buf, int len); $/;"	p	namespace:CRedisPro	signature:(const char *buf, int len)
eCmdType	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		CMD_TYPE eCmdType;						\/\/redis操作命令类型$/;"	m	struct:CRedisPro::redisRequest	access:public
element	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        vector<redisReply> element; $/;"	m	struct:CRedisPro::redisReply	access:public
elements	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        int elements;$/;"	m	struct:CRedisPro::redisReply	access:public
integer	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        long long integer;$/;"	m	struct:CRedisPro::redisReply	access:public
len	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        int len;$/;"	m	struct:CRedisPro::redisReply	access:public
mapField2Value	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		map<string, string> mapField2Value;		\/\/hash数据类型的key->value列表$/;"	m	struct:CRedisPro::redisRequest	access:public
pack	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack(const redisRequest &stReq, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const redisRequest &stReq, char *pszBuf, int &iLen)
pack	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack(const string &key, const string &binary, char *buffer, int &len);$/;"	p	namespace:CRedisPro	signature:(const string &key, const string &binary, char *buffer, int &len)
pack	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack(const string &key, const string &binary, const string &time, char *buffer, int &len);$/;"	p	namespace:CRedisPro	signature:(const string &key, const string &binary, const string &time, char *buffer, int &len)
pack	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack(vector<string> &vecQuery, char *buffer, int &len);$/;"	p	namespace:CRedisPro	signature:(vector<string> &vecQuery, char *buffer, int &len)
pack_del	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_del(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
pack_expire	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_expire(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
pack_get	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_get(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
pack_hclear	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_hclear(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
pack_hgetall	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_hgetall(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
pack_hincrby	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_hincrby(const string &strKey, const string &strField, const string &strCount, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strField, const string &strCount, char *pszBuf, int &iLen)
pack_hmget	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_hmget(const string &strKey, const vector<string> &vecFields, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const vector<string> &vecFields, char *pszBuf, int &iLen)
pack_hmset	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_hmset(const string &strKey, const map<string, string> &mapField2Value, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const map<string, string> &mapField2Value, char *pszBuf, int &iLen)
pack_incr	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_incr(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
pack_incrby	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_incrby(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
pack_sadd	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_sadd(const string &strKey, const vector<string> &vecElems, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const vector<string> &vecElems, char *pszBuf, int &iLen)
pack_scard	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_scard(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
pack_set	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_set(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
pack_setex	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_setex(const string &strKey, const string &strValue, const string &strTime, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, const string &strTime, char *pszBuf, int &iLen)
pack_setnx	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_setnx(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
pack_sismember	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_sismember(const string &strKey, const string &strElem, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strElem, char *pszBuf, int &iLen)
pack_smembers	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_smembers(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
pack_srem	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_srem(const string &strKey, const vector<string> &vecElems, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const vector<string> &vecElems, char *pszBuf, int &iLen)
pack_zadd	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_zadd(const string &strKey, const string &strScore, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strScore, const string &strValue, char *pszBuf, int &iLen)
pack_zcard	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int pack_zcard(const string &strKey, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, char *pszBuf, int &iLen)
pack_zcount	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zcount(const string &strKey, const string &strStart, const string &strEnd, bool bLessFlag, bool bGreateFlag, bool bIsSsdbFlag, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strStart, const string &strEnd, bool bLessFlag, bool bGreateFlag, bool bIsSsdbFlag, char *pszBuf, int &iLen)
pack_zincrby	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zincrby(const string &strKey, const string &strField, const string &strCount, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strField, const string &strCount, char *pszBuf, int &iLen)
pack_zrange	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrange(const string &strKey, const string &strStart, const string &strEnd, char *pszBuf, int &iLen, bool bWithScores=false);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strStart, const string &strEnd, char *pszBuf, int &iLen, bool bWithScores=false)
pack_zrangebyscore	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrangebyscore(const string &strKey, const string &strStart, const string &strEnd, const string &strLimit, bool bWithScores, bool bLessFlag, bool bGreateFlag, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strStart, const string &strEnd, const string &strLimit, bool bWithScores, bool bLessFlag, bool bGreateFlag, char *pszBuf, int &iLen)
pack_zrank	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrank(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
pack_zrem	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrem(const string &strKey, const vector<string> &vecValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const vector<string> &vecValue, char *pszBuf, int &iLen)
pack_zremrangebyrank	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zremrangebyrank(const string &strKey, const string &strStart, const string &strEnd, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strStart, const string &strEnd, char *pszBuf, int &iLen)
pack_zrevrange	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrevrange(const string &strKey, const string &strStart, const string &strEnd, char *pszBuf, int &iLen, bool bWithScores=false);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strStart, const string &strEnd, char *pszBuf, int &iLen, bool bWithScores=false)
pack_zrevrangebyscore	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrevrangebyscore(const string &strKey, const string &strStart, const string &strEnd, const string &strLimit, bool bWithScores, bool bLessFlag, bool bGreateFlag, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strStart, const string &strEnd, const string &strLimit, bool bWithScores, bool bLessFlag, bool bGreateFlag, char *pszBuf, int &iLen)
pack_zrevrank	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zrevrank(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
pack_zscore	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	int pack_zscore(const string &strKey, const string &strValue, char *pszBuf, int &iLen);$/;"	p	namespace:CRedisPro	signature:(const string &strKey, const string &strValue, char *pszBuf, int &iLen)
printRedisReply	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    string printRedisReply(const redisReply &reply);$/;"	p	namespace:CRedisPro	signature:(const redisReply &reply)
process_bulk_item	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int process_bulk_item(string::const_iterator &pos, string::const_iterator end, redisReply &reply);$/;"	p	namespace:CRedisPro	signature:(string::const_iterator &pos, string::const_iterator end, redisReply &reply)
process_item	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int process_item(string::const_iterator &pos, string::const_iterator end, redisReply &reply);$/;"	p	namespace:CRedisPro	signature:(string::const_iterator &pos, string::const_iterator end, redisReply &reply)
process_line_item	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int process_line_item(string::const_iterator &pos, string::const_iterator end, redisReply &reply);$/;"	p	namespace:CRedisPro	signature:(string::const_iterator &pos, string::const_iterator end, redisReply &reply)
process_multi_bulk_item	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int process_multi_bulk_item(string::const_iterator &pos, string::const_iterator end, redisReply &reply);$/;"	p	namespace:CRedisPro	signature:(string::const_iterator &pos, string::const_iterator end, redisReply &reply)
redisReply	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        redisReply()$/;"	f	struct:CRedisPro::redisReply	access:public	signature:()
redisReply	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    struct redisReply$/;"	s	namespace:CRedisPro
redisRequest	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		redisRequest()$/;"	f	struct:CRedisPro::redisRequest	access:public	signature:()
redisRequest	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^	struct redisRequest$/;"	s	namespace:CRedisPro
seek_new_line	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int seek_new_line(string::const_iterator pos, string::const_iterator end, string::const_iterator &res);$/;"	p	namespace:CRedisPro	signature:(string::const_iterator pos, string::const_iterator end, string::const_iterator &res)
str	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        string str;$/;"	m	struct:CRedisPro::redisReply	access:public
strEnd	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strEnd;							\/\/sorted set数据类型里zrangebyscore等命令的参数，结束权重$/;"	m	struct:CRedisPro::redisRequest	access:public
strField	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strField;						\/\/hash数据类型的域字段值。$/;"	m	struct:CRedisPro::redisRequest	access:public
strKey	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strKey;							\/\/数据的key$/;"	m	struct:CRedisPro::redisRequest	access:public
strLimit	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strLimit;						\/\/sorted set数据类型里zrangebyscore等命令的参数，限制字段$/;"	m	struct:CRedisPro::redisRequest	access:public
strScore	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strScore;						\/\/sorted set数据类型的权重值$/;"	m	struct:CRedisPro::redisRequest	access:public
strStart	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strStart;						\/\/sorted set数据类型里zrangebyscore等命令的参数，起始权重$/;"	m	struct:CRedisPro::redisRequest	access:public
strTime	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strTime;							\/\/过期时间$/;"	m	struct:CRedisPro::redisRequest	access:public
strValue	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		string strValue;						\/\/value字段$/;"	m	struct:CRedisPro::redisRequest	access:public
type	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^        int type;$/;"	m	struct:CRedisPro::redisReply	access:public
unpack	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int unpack(const string &buffer, int len, redisReply &reply);$/;"	p	namespace:CRedisPro	signature:(const string &buffer, int len, redisReply &reply)
unpack	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^    int unpack(const string &rspbuffer, vector<redisReply> &vecReply, string &restbuffer);$/;"	p	namespace:CRedisPro	signature:(const string &rspbuffer, vector<redisReply> &vecReply, string &restbuffer)
vecField	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		vector<string> vecField;				\/\/hash数据类型的域字段列表。$/;"	m	struct:CRedisPro::redisRequest	access:public
vecKey	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		vector<string> vecKey;					\/\/string时批量处理的key$/;"	m	struct:CRedisPro::redisRequest	access:public
vecValue	/usr/local/commlib/platformlib/redis_protocol/include/redis_protocol.h	/^		vector<string> vecValue;				\/\/hash或者sorted set数据类型的值字段列表。$/;"	m	struct:CRedisPro::redisRequest	access:public
