!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.8	//
E_ATTACH_SHM	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_ATTACH_SHM = 1, E_CHECK_SHM, E_CONFIG_ID_NOT_FOUND, E_INIT_LINKTABLE, E_REINIT};$/;"	e	enum:UnifiedConfigAPI::__anon1
E_CHECK_KEY	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_SHM_INDEX_INVALID = 1, E_KEY_NOT_FOUND, E_LINKTABLE, E_PARSE_PACKET, E_CHECK_KEY, E_NOT_INIT};$/;"	e	enum:UnifiedConfigAPI::__anon2
E_CHECK_SHM	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_ATTACH_SHM = 1, E_CHECK_SHM, E_CONFIG_ID_NOT_FOUND, E_INIT_LINKTABLE, E_REINIT};$/;"	e	enum:UnifiedConfigAPI::__anon1
E_CONFIG_ID_NOT_FOUND	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_ATTACH_SHM = 1, E_CHECK_SHM, E_CONFIG_ID_NOT_FOUND, E_INIT_LINKTABLE, E_REINIT};$/;"	e	enum:UnifiedConfigAPI::__anon1
E_INIT_LINKTABLE	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_ATTACH_SHM = 1, E_CHECK_SHM, E_CONFIG_ID_NOT_FOUND, E_INIT_LINKTABLE, E_REINIT};$/;"	e	enum:UnifiedConfigAPI::__anon1
E_KEY_NOT_FOUND	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_SHM_INDEX_INVALID = 1, E_KEY_NOT_FOUND, E_LINKTABLE, E_PARSE_PACKET, E_CHECK_KEY, E_NOT_INIT};$/;"	e	enum:UnifiedConfigAPI::__anon2
E_LINKTABLE	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_SHM_INDEX_INVALID = 1, E_KEY_NOT_FOUND, E_LINKTABLE, E_PARSE_PACKET, E_CHECK_KEY, E_NOT_INIT};$/;"	e	enum:UnifiedConfigAPI::__anon2
E_NOT_INIT	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_SHM_INDEX_INVALID = 1, E_KEY_NOT_FOUND, E_LINKTABLE, E_PARSE_PACKET, E_CHECK_KEY, E_NOT_INIT};$/;"	e	enum:UnifiedConfigAPI::__anon2
E_PARSE_PACKET	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_SHM_INDEX_INVALID = 1, E_KEY_NOT_FOUND, E_LINKTABLE, E_PARSE_PACKET, E_CHECK_KEY, E_NOT_INIT};$/;"	e	enum:UnifiedConfigAPI::__anon2
E_REINIT	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_ATTACH_SHM = 1, E_CHECK_SHM, E_CONFIG_ID_NOT_FOUND, E_INIT_LINKTABLE, E_REINIT};$/;"	e	enum:UnifiedConfigAPI::__anon1
E_SHM_INDEX_INVALID	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_SHM_INDEX_INVALID = 1, E_KEY_NOT_FOUND, E_LINKTABLE, E_PARSE_PACKET, E_CHECK_KEY, E_NOT_INIT};$/;"	e	enum:UnifiedConfigAPI::__anon2
UnifiedConfigAPI	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    UnifiedConfigAPI();$/;"	p	class:UnifiedConfigAPI	access:public	signature:()
UnifiedConfigAPI	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    UnifiedConfigAPI(const UnifiedConfigAPI&);$/;"	p	class:UnifiedConfigAPI	access:private	signature:(const UnifiedConfigAPI&)
UnifiedConfigAPI	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^class UnifiedConfigAPI {$/;"	c
UnifiedConfigAPI::E_ATTACH_SHM	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_ATTACH_SHM = 1, E_CHECK_SHM, E_CONFIG_ID_NOT_FOUND, E_INIT_LINKTABLE, E_REINIT};$/;"	e	enum:UnifiedConfigAPI::__anon1
UnifiedConfigAPI::E_CHECK_KEY	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_SHM_INDEX_INVALID = 1, E_KEY_NOT_FOUND, E_LINKTABLE, E_PARSE_PACKET, E_CHECK_KEY, E_NOT_INIT};$/;"	e	enum:UnifiedConfigAPI::__anon2
UnifiedConfigAPI::E_CHECK_SHM	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_ATTACH_SHM = 1, E_CHECK_SHM, E_CONFIG_ID_NOT_FOUND, E_INIT_LINKTABLE, E_REINIT};$/;"	e	enum:UnifiedConfigAPI::__anon1
UnifiedConfigAPI::E_CONFIG_ID_NOT_FOUND	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_ATTACH_SHM = 1, E_CHECK_SHM, E_CONFIG_ID_NOT_FOUND, E_INIT_LINKTABLE, E_REINIT};$/;"	e	enum:UnifiedConfigAPI::__anon1
UnifiedConfigAPI::E_INIT_LINKTABLE	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_ATTACH_SHM = 1, E_CHECK_SHM, E_CONFIG_ID_NOT_FOUND, E_INIT_LINKTABLE, E_REINIT};$/;"	e	enum:UnifiedConfigAPI::__anon1
UnifiedConfigAPI::E_KEY_NOT_FOUND	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_SHM_INDEX_INVALID = 1, E_KEY_NOT_FOUND, E_LINKTABLE, E_PARSE_PACKET, E_CHECK_KEY, E_NOT_INIT};$/;"	e	enum:UnifiedConfigAPI::__anon2
UnifiedConfigAPI::E_LINKTABLE	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_SHM_INDEX_INVALID = 1, E_KEY_NOT_FOUND, E_LINKTABLE, E_PARSE_PACKET, E_CHECK_KEY, E_NOT_INIT};$/;"	e	enum:UnifiedConfigAPI::__anon2
UnifiedConfigAPI::E_NOT_INIT	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_SHM_INDEX_INVALID = 1, E_KEY_NOT_FOUND, E_LINKTABLE, E_PARSE_PACKET, E_CHECK_KEY, E_NOT_INIT};$/;"	e	enum:UnifiedConfigAPI::__anon2
UnifiedConfigAPI::E_PARSE_PACKET	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_SHM_INDEX_INVALID = 1, E_KEY_NOT_FOUND, E_LINKTABLE, E_PARSE_PACKET, E_CHECK_KEY, E_NOT_INIT};$/;"	e	enum:UnifiedConfigAPI::__anon2
UnifiedConfigAPI::E_REINIT	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_ATTACH_SHM = 1, E_CHECK_SHM, E_CONFIG_ID_NOT_FOUND, E_INIT_LINKTABLE, E_REINIT};$/;"	e	enum:UnifiedConfigAPI::__anon1
UnifiedConfigAPI::E_SHM_INDEX_INVALID	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    enum {E_SHM_INDEX_INVALID = 1, E_KEY_NOT_FOUND, E_LINKTABLE, E_PARSE_PACKET, E_CHECK_KEY, E_NOT_INIT};$/;"	e	enum:UnifiedConfigAPI::__anon2
UnifiedConfigAPI::UnifiedConfigAPI	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    UnifiedConfigAPI();$/;"	p	class:UnifiedConfigAPI	access:public	signature:()
UnifiedConfigAPI::UnifiedConfigAPI	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    UnifiedConfigAPI(const UnifiedConfigAPI&);$/;"	p	class:UnifiedConfigAPI	access:private	signature:(const UnifiedConfigAPI&)
UnifiedConfigAPI::displayAllConfig	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    std::string displayAllConfig(int effectShmIndex = 0);$/;"	p	class:UnifiedConfigAPI	access:public	signature:(int effectShmIndex = 0)
UnifiedConfigAPI::get	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    int get(std::string key, std::vector<std::map<std::string, std::string> >& values, int effectShmIndex = 0);$/;"	p	class:UnifiedConfigAPI	access:public	signature:(std::string key, std::vector<std::map<std::string, std::string> >& values, int effectShmIndex = 0)
UnifiedConfigAPI::getCurrentEffectShmIndex	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    uint8_t getCurrentEffectShmIndex();$/;"	p	class:UnifiedConfigAPI	access:public	signature:()
UnifiedConfigAPI::getLastUpdateTimestamp	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    uint32_t getLastUpdateTimestamp();$/;"	p	class:UnifiedConfigAPI	access:public	signature:()
UnifiedConfigAPI::init	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    int init(int configId);$/;"	p	class:UnifiedConfigAPI	access:public	signature:(int configId)
UnifiedConfigAPI::operator =	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    const UnifiedConfigAPI& operator=(const UnifiedConfigAPI&);$/;"	p	class:UnifiedConfigAPI	access:private	signature:(const UnifiedConfigAPI&)
UnifiedConfigAPI::shmPtr	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    void* shmPtr;$/;"	m	class:UnifiedConfigAPI	access:private
UnifiedConfigAPI::stFirstLinkTable	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    struct LinkTable* stFirstLinkTable;$/;"	m	class:UnifiedConfigAPI	typeref:struct:UnifiedConfigAPI::LinkTable	access:private
UnifiedConfigAPI::stSecondLinkTable	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    struct LinkTable* stSecondLinkTable;$/;"	m	class:UnifiedConfigAPI	typeref:struct:UnifiedConfigAPI::LinkTable	access:private
UnifiedConfigAPI::tableSummary	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    struct UnifiedConfigTableSummary* tableSummary;$/;"	m	class:UnifiedConfigAPI	typeref:struct:UnifiedConfigAPI::UnifiedConfigTableSummary	access:private
UnifiedConfigAPI::~UnifiedConfigAPI	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    ~UnifiedConfigAPI();$/;"	p	class:UnifiedConfigAPI	access:public	signature:()
displayAllConfig	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    std::string displayAllConfig(int effectShmIndex = 0);$/;"	p	class:UnifiedConfigAPI	access:public	signature:(int effectShmIndex = 0)
get	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    int get(std::string key, std::vector<std::map<std::string, std::string> >& values, int effectShmIndex = 0);$/;"	p	class:UnifiedConfigAPI	access:public	signature:(std::string key, std::vector<std::map<std::string, std::string> >& values, int effectShmIndex = 0)
getCurrentEffectShmIndex	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    uint8_t getCurrentEffectShmIndex();$/;"	p	class:UnifiedConfigAPI	access:public	signature:()
getLastUpdateTimestamp	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    uint32_t getLastUpdateTimestamp();$/;"	p	class:UnifiedConfigAPI	access:public	signature:()
init	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    int init(int configId);$/;"	p	class:UnifiedConfigAPI	access:public	signature:(int configId)
operator =	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    const UnifiedConfigAPI& operator=(const UnifiedConfigAPI&);$/;"	p	class:UnifiedConfigAPI	access:private	signature:(const UnifiedConfigAPI&)
shmPtr	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    void* shmPtr;$/;"	m	class:UnifiedConfigAPI	access:private
stFirstLinkTable	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    struct LinkTable* stFirstLinkTable;$/;"	m	class:UnifiedConfigAPI	typeref:struct:UnifiedConfigAPI::LinkTable	access:private
stSecondLinkTable	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    struct LinkTable* stSecondLinkTable;$/;"	m	class:UnifiedConfigAPI	typeref:struct:UnifiedConfigAPI::LinkTable	access:private
tableSummary	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    struct UnifiedConfigTableSummary* tableSummary;$/;"	m	class:UnifiedConfigAPI	typeref:struct:UnifiedConfigAPI::UnifiedConfigTableSummary	access:private
~UnifiedConfigAPI	/usr/local/commlib/platformlib/unified_config_api/include/UnifiedConfigAPI.h	/^    ~UnifiedConfigAPI();$/;"	p	class:UnifiedConfigAPI	access:public	signature:()
